### ISSUE TITLE
LaTeX and new cross-referencing method

### ISSUE THREAD

**Issue by matteofg** [gusbrs/zref-check#2]
Hi gusbrs,
I wanted to know what you think about the new cross-referencing method implemented in LaTeX (ltnews38) and how this will affect the development of your 'zref-based' packages.

Thank you

**Comment by gusbrs** [comment]
Hi @matteo339 , I've seen it, and it's pretty cool. It is functionally equivalent to `zref` and conceptually very similar to it (and explicitly so, as you've probably seen). Indeed, it was made by Ulrike Fischer for the purposes of the tagging project, and she is (as far as I can tell) the main responsible for maintaining `zref`. It has actually existed for some time, but was now made public.

But the most impactful recent kernel change (for `zref-clever` and Co., that is) was the new `label` hook, made available in the previous release, and which `zref-clever` promptly seized. With it label setting has much improved, since now people can use the standard `\label` and the package has much less trouble with handling special cases.

> how this will affect the development of your 'zref-based' packages

Not much really. As I said, they are functionally equivalent, and `zref` is doing it's job well. There's no reason to change. Also, it'd be weird having some packages called `zref-something` not using `zref` ;-). If I was starting with the packages now, it'd be another matter, but the ship has sailed.

**Comment by matteofg** [comment]
Thank you for sharing your considerations.
